### ISSUE TITLE
Error in combine_img_prediction

### ISSUE THREAD

**Issue by stefat77** [jakeret/tf_unet#65] opened 2017-06-23 13:12 UTC
Hi, 
I have a trouble while running my code:

```
# Import data
print('Loading dataset...\n')
X_data = np.load(DATASET_FOLDER+"X_data.npy")
y_data = np.load(DATASET_FOLDER+"y_data.npy")
X_test = np.load(DATASET_FOLDER+"X_test.npy")
y_test = np.load(DATASET_FOLDER+"y_test.npy")

print("TRAIN data shape: ", X_data.shape)
print("TRAIN labels shape", y_data.shape)
print("TEST data shape: ", X_test.shape)
print("TEST labels shape: ", y_test.shape)

X_data = np.float32(X_data)
y_data = np.float32(y_data)
X_test = np.float32(X_test)
y_test = np.float32(y_test)

training_iters = 20
epochs = 100
dropout = 0.75 # Dropout, probability to keep units
display_step = 2
restore = False
 
data_provider = image_util.SimpleDataProvider(X_data, y_data, channels=2, n_class=1)

net = unet.Unet(channels=2, n_class=1, layers=4, features_root=64, cost="dice_coefficient")
    
trainer = unet.Trainer(net, optimizer="adam")
path = trainer.train(data_provider, "./unet_trained", training_iters=training_iters, epochs=epochs, dropout=dropout, display_step=display_step, restore=restore)
     
prediction = net.predict(path, X_test)
     
print("Testing error rate: {:.2f}%".format(unet.error_rate(prediction, util.crop_to_shape(y_test, prediction.shape))))
   
```

The error is:
```

Loading dataset...

TRAIN data shape:  (1560, 128, 128, 2)
TRAIN labels shape (1560, 128, 128)
TEST data shape:  (120, 128, 128, 2)
TEST labels shape:  (120, 128, 128)
2017-06-23 15:07:05,594 Layers 4, features 64, filter size 3x3, pool size: 2x2
2017-06-23 15:07:07,878 Removing '/home/stefano/Dropbox/DeepWave/prediction'
2017-06-23 15:07:07,878 Removing '/home/stefano/Dropbox/DeepWave/unet_trained'
2017-06-23 15:07:07,878 Allocating '/home/stefano/Dropbox/DeepWave/prediction'
2017-06-23 15:07:07,879 Allocating '/home/stefano/Dropbox/DeepWave/unet_trained'
2017-06-23 15:07:07.879575: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 15:07:07.879602: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 15:07:07.879615: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 15:07:10,201 Verification error= 0.0%, loss= -0.0000
Traceback (most recent call last):
  File "Unet.py", line 45, in <module>
    path = trainer.train(data_provider, "./unet_trained", training_iters=training_iters, epochs=epochs, dropout=dropout, display_step=display_step, restore=restore)
  File "./tf_unet/unet.py", line 404, in train
    pred_shape = self.store_prediction(sess, test_x, test_y, "_init")
  File "./tf_unet/unet.py", line 457, in store_prediction
    img = util.combine_img_prediction(batch_x, batch_y, prediction)
  File "/home/stefano/Dropbox/DeepWave/tf_unet/util.py", line 104, in combine_img_prediction
    to_rgb(crop_to_shape(gt[..., 1], pred.shape).reshape(-1, ny, 1)), 
IndexError: index 1 is out of bounds for axis 3 with size 1

```

combile_img_prediction function has the following argument shapes:
(4, 128, 128, 1) --> gt
(4, 128, 128, 2) --> data
(4, 36, 36, 1) --> pred

My datasets have the following shapes:
TRAIN data shape:  (1560, 128, 128, 2)
TRAIN labels shape (1560, 128, 128)
TEST data shape:  (120, 128, 128, 2)
TEST labels shape:  (120, 128, 128)

How can I solve the issue?
Thank you! :+1: 

EDIT: sorry.. obviously n_class was 2. I corrected the error... but now i have: 
```
Traceback (most recent call last):
  File "Unet.py", line 43, in <module>
    path = trainer.train(data_provider, "./unet_trained", training_iters=training_iters, epochs=epochs, dropout=dropout, display_step=display_step, restore=restore)
  File "./tf_unet/unet.py", line 403, in train
    test_x, test_y = data_provider(self.verification_batch_size)
  File "./tf_unet/image_util.py", line 89, in __call__
    train_data, labels = self._load_data_and_label()
  File "./tf_unet/image_util.py", line 50, in _load_data_and_label
    labels = self._process_labels(label)
  File "./tf_unet/image_util.py", line 65, in _process_labels
    labels[..., 0] = ~label
TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

```

**Comment by jakeret** [comment] 2017-06-23 14:18
For a binary classification task `tf_unet` is expecting a boolean label array.

Something like this might help:

> y_data = np.load(DATASET_FOLDER+"y_data.npy").astype(np.bool)

**Comment by stefat77** [comment] 2017-06-23 15:31
Thx for the answer :)

I casted my label arrays as booleans... but now I have the same error as before:

```
Loading dataset...

TRAIN data shape:  (1560, 128, 128, 2)
TRAIN labels shape (1560, 128, 128)
TEST data shape:  (120, 128, 128, 2)
TEST labels shape:  (120, 128, 128)
2017-06-23 17:27:44,948 Layers 4, features 64, filter size 3x3, pool size: 2x2
2017-06-23 17:27:47,566 Removing '/home/stefano/Dropbox/DeepWave/prediction'
2017-06-23 17:27:47,566 Removing '/home/stefano/Dropbox/DeepWave/unet_trained'
2017-06-23 17:27:47,566 Allocating '/home/stefano/Dropbox/DeepWave/prediction'
2017-06-23 17:27:47,566 Allocating '/home/stefano/Dropbox/DeepWave/unet_trained'
2017-06-23 17:27:47.567290: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 17:27:47.567318: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 17:27:47.567327: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 17:27:50,001 Verification error= 0.0%, loss= -0.5074
Traceback (most recent call last):
  File "Unet.py", line 48, in <module>
    path = trainer.train(data_provider, "./unet_trained", training_iters=training_iters, epochs=epochs, dropout=dropout, display_step=display_step, restore=restore)
  File "./tf_unet/unet.py", line 404, in train
    pred_shape = self.store_prediction(sess, test_x, test_y, "_init")
  File "./tf_unet/unet.py", line 457, in store_prediction
    img = util.combine_img_prediction(batch_x, batch_y, prediction)
  File "/home/stefano/Dropbox/DeepWave/tf_unet/util.py", line 106, in combine_img_prediction
    to_rgb(pred[..., 1].reshape(-1, ny, 1))), axis=1)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

```
with gt, data and pred with the following shapes in combile_img_prediction:
(4, 128, 128, 1) --> gt
(4, 128, 128, 2) --> data
(4, 36, 36, 1) --> pred

**Comment by jakeret** [comment] 2017-06-23 16:51
Hmm I think there is a bug in the [`to_rgb` function](https://github.com/jakeret/tf_unet/blob/master/tf_unet/util.py#L69). Looks like it only works if the data has 1 or 3 channels

**Comment by stefat77** [comment] 2017-06-23 17:29
ok. I try to see...
Thank you

**Comment by stefat77** [comment] 2017-06-23 18:17
Should combine_image_prediction receive arguments with common shape?
combine_image_prediction is only used to output an image in a given folder right?
I tried the following combine_image_function:

```
def combine_img_prediction(data, gt, pred):
    """
    Combines the data, grouth thruth and the prediction into one rgb image
    
    :param data: the data tensor
    :param gt: the ground thruth tensor
    :param pred: the prediction tensor
    
    :returns img: the concatenated rgb image 
    """
    ny = pred.shape[2]
    ch = data.shape[3]
    print(data.shape)
    print(gt.shape)
    print(pred.shape)
    img = np.eye(50)*255
    """
    print(to_rgb(crop_to_shape(data, pred.shape).reshape(-1, ny, ch)).shape)
    print(to_rgb(crop_to_shape(gt[..., 1], pred.shape).reshape(-1, ny, 1)).shape)
    print(to_rgb(pred[..., 1].reshape(-1, ny, 1)).shape)
    
    img = np.concatenate((to_rgb(crop_to_shape(data, pred.shape).reshape(-1, ny, ch)), 
                          to_rgb(crop_to_shape(gt[..., 1], pred.shape).reshape(-1, ny, 1)), 
                          to_rgb(pred[..., 1].reshape(-1, ny, 1))), axis=1)
    """
    return img
```

The terminal gives:
```
Loading dataset...

TRAIN data shape:  (1560, 128, 128, 2)
TRAIN labels shape (1560, 128, 128)
TEST data shape:  (120, 128, 128, 2)
TEST labels shape:  (120, 128, 128)
2017-06-23 20:10:13,643 Layers 4, features 64, filter size 3x3, pool size: 2x2
2017-06-23 20:10:16,020 Removing '/home/stefano/Dropbox/DeepWave/prediction'
2017-06-23 20:10:16,021 Removing '/home/stefano/Dropbox/DeepWave/unet_trained'
2017-06-23 20:10:16,021 Allocating '/home/stefano/Dropbox/DeepWave/prediction'
2017-06-23 20:10:16,022 Allocating '/home/stefano/Dropbox/DeepWave/unet_trained'
2017-06-23 20:10:16.022469: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 20:10:16.022493: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 20:10:16.022503: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 20:10:18,409 Verification error= 87.5%, loss= -0.4976
(4, 128, 128, 2)
(4, 128, 128, 2)
(4, 36, 36, 2)
2017-06-23 20:10:18,978 Start optimization
2017-06-23 20:10:20,691 Iter 0, Minibatch Loss= -0.5816, Training Accuracy= 1.0000, Minibatch error= 0.0%
2017-06-23 20:10:23,318 Iter 2, Minibatch Loss= -1.0000, Training Accuracy= 1.0000, Minibatch error= 0.0%
2017-06-23 20:10:26.026308: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Nan in summary histogram for: norm_grads
         [[Node: norm_grads = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](norm_grads/tag, Variable_37/read)]]
2017-06-23 20:10:26.026349: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Nan in summary histogram for: norm_grads
         [[Node: norm_grads = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](norm_grads/tag, Variable_37/read)]]
2017-06-23 20:10:26.026423: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Nan in summary histogram for: norm_grads
         [[Node: norm_grads = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](norm_grads/tag, Variable_37/read)]]
Traceback (most recent call last):
  File "/home/stefano/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1039, in _do_call
    return fn(*args)
  File "/home/stefano/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
    status, run_metadata)
  File "/home/stefano/anaconda3/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/stefano/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: norm_grads
         [[Node: norm_grads = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](norm_grads/tag, Variable_37/read)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Unet.py", line 48, in <module>
    path = trainer.train(data_provider, "./unet_trained", training_iters=training_iters, epochs=epochs, dropout=dropout, display_step=display_step, restore=restore)
  File "./tf_unet/unet.py", line 430, in train
    self.output_minibatch_stats(sess, summary_writer, step, batch_x, util.crop_to_shape(batch_y, pred_shape))
  File "./tf_unet/unet.py", line 473, in output_minibatch_stats
    self.net.keep_prob: 1.})
  File "/home/stefano/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/stefano/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/stefano/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/stefano/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: norm_grads
         [[Node: norm_grads = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](norm_grads/tag, Variable_37/read)]]

Caused by op 'norm_grads', defined at:
  File "Unet.py", line 48, in <module>
    path = trainer.train(data_provider, "./unet_trained", training_iters=training_iters, epochs=epochs, dropout=dropout, display_step=display_step, restore=restore)
  File "./tf_unet/unet.py", line 390, in train
    init = self._initialize(training_iters, output_path, restore)
  File "./tf_unet/unet.py", line 342, in _initialize
    tf.summary.histogram('norm_grads', self.norm_gradients_node)
  File "/home/stefano/anaconda3/lib/python3.6/site-packages/tensorflow/python/summary/summary.py", line 209, in histogram
    tag=scope.rstrip('/'), values=values, name=scope)
  File "/home/stefano/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 139, in _histogram_summary
    name=name)
  File "/home/stefano/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/stefano/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/stefano/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Nan in summary histogram for: norm_grads
         [[Node: norm_grads = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](norm_grads/tag, Variable_37/read)]]

```

**Comment by stefat77** [comment] 2017-06-25 21:49
Hi, I modified combine_img_prediction in order to concatenate 4 images: my two channels + label + prediction... but now I have another problem:
How can I obtain output prediction shape equal to the input shape?
My data samples have shape 128x128x2 but predictions have 88x88x2...

**Comment by jakeret** [comment] 2017-06-26 06:28
Great! Is this somehow reuseable for others? If so, would you mind to send me a PR?

This is an expected behaviour (see the original Ronneberger et al. paper). What works well is to mirror the edges of the images to create a larger input in order to compensate the loss

**Comment by stefat77** [comment] 2017-06-26 09:41
I changed the net from:
net = unet.Unet(channels=generator.channels, n_class=generator.n_class, layers=3, features_root=64, cost="dice_coefficient")

to:
net = unet.Unet(channels=generator.channels, n_class=generator.n_class, layers=4, features_root=128, cost="dice_coefficient")

but now the output prediction has size 36x36x2... is it still normal?

**Comment by stefat77** [comment] 2017-06-26 11:49
> Great! Is this somehow reuseable for others? If so, would you mind to send me a PR?

For now it is not reusable but I can do it next week. In these days i don't have so much free time, but I would be glad to help :)

**Comment by jakeret** [comment] 2017-06-26 18:11
This seems to happen if the gradients explode (See #28). So far I haven't found a definite solution to this.

**Comment by stefat77** [comment] 2017-06-27 15:13
Thank you for the answer... you are very patient.
I have another issue... this is my terminal output:

```
TRAIN data shape:  (1080, 256, 256, 2)
TRAIN labels shape (1080, 256, 256)
TEST data shape:  (120, 256, 256, 2)
TEST labels shape:  (120, 256, 256)
2017-06-27 17:01:24,657 Layers 3, features 64, filter size 3x3, pool size: 2x2
2017-06-27 17:01:26,164 Removing '/home/stefano/Dropbox/DeepWave/prediction'
2017-06-27 17:01:26,164 Removing '/home/stefano/Dropbox/DeepWave/unet_trained'
2017-06-27 17:01:26,164 Allocating '/home/stefano/Dropbox/DeepWave/prediction'
2017-06-27 17:01:26,164 Allocating '/home/stefano/Dropbox/DeepWave/unet_trained'
2017-06-27 17:01:26.165215: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-27 17:01:26.165233: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-27 17:01:26.165242: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-27 17:01:38,682 Verification error= 100.0%, loss= -0.4882
2017-06-27 17:01:39,196 Start optimization
2017-06-27 17:01:48,665 Iter 0, Minibatch Loss= -0.5830, Training Accuracy= 1.0000, Minibatch error= 0.0%
2017-06-27 17:02:05,571 Iter 2, Minibatch Loss= -0.7644, Training Accuracy= 1.0000, Minibatch error= 0.0%
2017-06-27 17:02:22,366 Iter 4, Minibatch Loss= -0.9726, Training Accuracy= 1.0000, Minibatch error= 0.0%
2017-06-27 17:02:39,085 Iter 6, Minibatch Loss= -0.9947, Training Accuracy= 1.0000, Minibatch error= 0.0%
2017-06-27 17:02:57,761 Iter 8, Minibatch Loss= -0.9972, Training Accuracy= 1.0000, Minibatch error= 0.0%
2017-06-27 17:03:16,034 Iter 10, Minibatch Loss= -0.9982, Training Accuracy= 1.0000, Minibatch error= 0.0%
2017-06-27 17:03:34,933 Iter 12, Minibatch Loss= -0.9987, Training Accuracy= 1.0000, Minibatch error= 0.0%
2017-06-27 17:03:54,922 Iter 14, Minibatch Loss= -0.5565, Training Accuracy= 0.5566, Minibatch error= 44.3%
2017-06-27 17:04:17,774 Iter 16, Minibatch Loss= -0.9991, Training Accuracy= 1.0000, Minibatch error= 0.0%
2017-06-27 17:04:35,185 Iter 18, Minibatch Loss= -0.8922, Training Accuracy= 0.8927, Minibatch error= 10.7%
2017-06-27 17:04:44,692 Epoch 0, Average loss: -0.8885, learning rate: 0.2000
2017-06-27 17:04:58,064 Verification error= 0.0%, loss= -0.9994
2017-06-27 17:04:59,293 Optimization Finished!
INFO:tensorflow:Restoring parameters from ./unet_trained/model.cpkt
2017-06-27 17:05:00,109 Restoring parameters from ./unet_trained/model.cpkt
2017-06-27 17:05:00,298 Model restored from file: ./unet_trained/model.cpkt
PREDICTION (20, 216, 216, 2)

```

I cannot understand why train accuracy is almost every iteration = 1... also minibatch error = 0%.

This is my code... maybe I did again something wrong:

```
print('Loading dataset...\n')
X_data = np.load(DATASET_FOLDER+"X_data.npy")
X_test = np.load(DATASET_FOLDER+"X_test.npy")
y_data = np.load(DATASET_FOLDER+"y_data.npy")
y_test = np.load(DATASET_FOLDER+"y_test.npy")

print("TRAIN data shape: ", X_data.shape)
print("TRAIN labels shape", y_data.shape)
print("TEST data shape: ", X_test.shape)
print("TEST labels shape: ", y_test.shape)

X_data = X_data.astype(np.float32)
y_data = y_data.astype(np.bool)
X_test = X_test.astype(np.float32)
y_test = y_test.astype(np.bool)

training_iters = 20
epochs = 1
dropout = 0.75 # Dropout, probability to keep units
display_step = 2
restore = False
 
generator = image_util.SimpleDataProvider(X_data, y_data, channels=2, n_class=2)
test_generator = image_util.SimpleDataProvider(X_test, y_test, channels=2, n_class=2)

net = unet.Unet(channels=generator.channels, n_class=generator.n_class, layers=3, features_root=64, cost="dice_coefficient")
    
trainer = unet.Trainer(net, optimizer="momentum", opt_kwargs=dict(momentum=0.2))
path = trainer.train(generator, "./unet_trained", training_iters=training_iters, epochs=epochs, dropout=dropout, display_step=display_step, restore=restore)
     
```

About dataset... the dataset have shape:
TRAIN data shape:  (1080, 256, 256, 2)
TRAIN labels shape (1080, 256, 256)
TEST data shape:  (120, 256, 256, 2)
TEST labels shape:  (120, 256, 256)

After conversion X_test, X_data have float32 values between 0 and 255.
y_test and y_data are boolean matrices.

Thanks for your help.

**Comment by stefat77** [comment] 2017-06-28 16:06
I found the problem... the generator made with SimpleDataProvider creates a lot of blank images 0.o''

```
generator = image_util.SimpleDataProvider(X_data, y_data, channels=2, n_class=2)
s, t = generator(1000)
```
Almost every channel in s in a zero image and almost every t image is composed by a full True matrix and a full False matrix

**Comment by jakeret** [comment] 2017-06-28 17:09
From this I'm somehow deriving that the code is working alright and that there is some difference between the test and train data (structure)

**Comment by stefat77** [comment] 2017-06-28 17:42
I removed yesterday all black images in my dataset.
Also if:
generator = image_util.SimpleDataProvider(X_data[0:100,:,:,:], y_data[0:100,:,:], channels=2, n_class=2)
s, t = generator(100)

...works properly

**Comment by stefat77** [comment] 2017-06-28 20:05
You are right! :+1: I's my fault
Sorry for the stupid question :)

**Comment by jakeret** [comment] 2017-06-29 17:20
No worries. I'm closing this. Feel free to reopen if anything pops up again.

**Closed by jakeret** 2017-06-29 17:20 UTC
Labels: bug
